// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "drdgvhbh/discordbot/internal/entity"
import mock "github.com/stretchr/testify/mock"

// CharacterRepository is an autogenerated mock type for the CharacterRepository type
type CharacterRepository struct {
	mock.Mock
}

// SearchCharactersByName provides a mock function with given fields: name
func (_m *CharacterRepository) SearchCharactersByName(name string) ([]*entity.AnimeCharacter, error) {
	ret := _m.Called(name)

	var r0 []*entity.AnimeCharacter
	if rf, ok := ret.Get(0).(func(string) []*entity.AnimeCharacter); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AnimeCharacter)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
