// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import api "drdgvhbh/discordbot/internal/stock/api"
import entity "drdgvhbh/discordbot/internal/entity"
import mock "github.com/stretchr/testify/mock"

// StockDataTransferMapper is an autogenerated mock type for the StockDataTransferMapper type
type StockDataTransferMapper struct {
	mock.Mock
}

// CreateDTOFrom provides a mock function with given fields: _a0
func (_m *StockDataTransferMapper) CreateDTOFrom(_a0 *entity.Stock) *api.Stock {
	ret := _m.Called(_a0)

	var r0 *api.Stock
	if rf, ok := ret.Get(0).(func(*entity.Stock) *api.Stock); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Stock)
		}
	}

	return r0
}

// CreateStockFrom provides a mock function with given fields: _a0
func (_m *StockDataTransferMapper) CreateStockFrom(_a0 *api.Stock) *entity.Stock {
	ret := _m.Called(_a0)

	var r0 *entity.Stock
	if rf, ok := ret.Get(0).(func(*api.Stock) *entity.Stock); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Stock)
		}
	}

	return r0
}
