settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: discordbot
    path: .
    commands: {}
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor
        - ./internal/di/wire_gen.go
      scripts:
        - type: after
          command: make pipeline
