// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"Drd-Discord-Bot/bot/src/db/pg"
	"Drd-Discord-Bot/bot/src/user/api"
	"Drd-Discord-Bot/bot/src/user/mapper"
)

// Injectors from wire.go:

func InitializeUserRepository() (*api.UserRepository, error) {
	config := pg.ProvideConfig()
	db := pg.ProvideConnector(config)
	userMapper := mapper.CreateUserMapper()
	userRepository := api.CreateUserRepository(db, userMapper)
	return userRepository, nil
}
