// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	cli2 "drdgvhbh/discordbot/internal/cli"
	"drdgvhbh/discordbot/internal/db/pg"
	"drdgvhbh/discordbot/internal/discord/bot"
	"drdgvhbh/discordbot/internal/discord/bot/commands"
	"drdgvhbh/discordbot/internal/user/api"
	"drdgvhbh/discordbot/internal/user/entity"
	"drdgvhbh/discordbot/internal/user/mapper"
	"github.com/bwmarrin/discordgo"
	"github.com/urfave/cli"
)

// Injectors from wire.go:

func InitializeUserRepository() *api.UserRepository {
	config := pg.ProvideConfig()
	db := pg.ProvideConnector(config)
	userMapper := mapper.CreateUserMapper()
	userRepository := api.CreateUserRepository(db, userMapper)
	return userRepository
}

func InitializeCLI() *cli.App {
	config := cli2.ProvideConfig()
	app := cli2.ProvideCLI(config)
	return app
}

func InitializeDiscordBot() *discordgo.Session {
	config := bot.ProvideConfig()
	session := bot.ProvideDiscordBot(config)
	return session
}

// wire.go:

func InitializeRegisterUserCommandFactory(
	user *entity.User,
) *commands.RegisterUserCommandFactory {
	return commands.CreateRegisterUserCommandFactory(InitializeUserRepository(), user)
}
