// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	api4 "drdgvhbh/discordbot/internal/anime/anime/api"
	mapper4 "drdgvhbh/discordbot/internal/anime/anime/mapper"
	api3 "drdgvhbh/discordbot/internal/anime/character/api"
	mapper3 "drdgvhbh/discordbot/internal/anime/character/mapper"
	cli2 "drdgvhbh/discordbot/internal/cli"
	"drdgvhbh/discordbot/internal/db/pg"
	"drdgvhbh/discordbot/internal/discord/bot"
	"drdgvhbh/discordbot/internal/discord/bot/commands"
	api2 "drdgvhbh/discordbot/internal/stock/api"
	mapper2 "drdgvhbh/discordbot/internal/stock/mapper"
	"drdgvhbh/discordbot/internal/user/api"
	"drdgvhbh/discordbot/internal/user/mapper"
	"github.com/bwmarrin/discordgo"
	"github.com/urfave/cli"
)

// Injectors from wire.go:

func InitializeUserRepository() *api.UserRepository {
	config := pg.ProvideConfig()
	connector := pg.ProvideConnector(config)
	userDataTransferMapper := mapper.CreateUserMapper()
	userRepository := ProvideUserRepository(connector, userDataTransferMapper)
	return userRepository
}

func InitializeStockRepository() *api2.StockRepository {
	config := pg.ProvideConfig()
	connector := pg.ProvideConnector(config)
	stockDataTransferMapper := mapper2.CreateStockMapper()
	stockRepository := ProvideStockRepository(connector, stockDataTransferMapper)
	return stockRepository
}

func InitializeCharacterRepository() *api3.CharacterRepository {
	characterMapper := mapper3.ProvideCharacterMapper()
	characterRepository := api3.ProvideCharacterRepository(characterMapper)
	return characterRepository
}

func InitializeCLI() *cli.App {
	config := cli2.ProvideConfig()
	app := cli2.ProvideCLI(config)
	return app
}

func InitializeDiscordBot() *discordgo.Session {
	config := bot.ProvideConfig()
	session := bot.ProvideDiscordBot(config)
	return session
}

func InitializeRegisterUserCommandFactory() *commands.RegisterUserCommandFactory {
	config := pg.ProvideConfig()
	connector := pg.ProvideConnector(config)
	userDataTransferMapper := mapper.CreateUserMapper()
	userRepository := ProvideUserRepository(connector, userDataTransferMapper)
	logrusLogger := ProvideLogger()
	userRepositoryLogger := ProvideUserRepositoryLogger(userRepository, logrusLogger)
	registerUserCommandFactory := commands.CreateRegisterUserCommandFactory(userRepositoryLogger)
	return registerUserCommandFactory
}

func InitializeAnimeStockQuoteCommandFactory() *commands.AnimeStockQuoteCommandFactory {
	config := pg.ProvideConfig()
	connector := pg.ProvideConnector(config)
	stockDataTransferMapper := mapper2.CreateStockMapper()
	stockRepository := ProvideStockRepository(connector, stockDataTransferMapper)
	logrusLogger := ProvideLogger()
	stockRepositoryLogger := ProvideStockRepositoryLogger(stockRepository, logrusLogger)
	animeMapper := mapper4.ProvideAnimeMapper()
	animeRepository := api4.ProvideAnimeRepository(animeMapper)
	stockInteractorImp := ProvideStockInteractor(stockRepositoryLogger, animeRepository)
	animeStockQuoteCommandFactory := commands.ProvideAnimeStockQuoteCommandFactory(stockInteractorImp)
	return animeStockQuoteCommandFactory
}

// wire.go:

func InitializeAnimeCommand(
	subCommands []cli.Command,
) *cli.Command {
	return commands.ProvideAnimeCommand(subCommands)
}
